// A scanner converts an arbitrary watch source into a list of standardised
// findings. New source kinds (RSS, Atom, HTML scraping, GitHub API, etc.)
// implement this interface. Scanners must:
//   - Be safe to run repeatedly (idempotent).
//   - Never raise on a single bad item; return what they can.
//   - Honour robots.txt and rate limits of the upstream source.
//   - Time out within 30 seconds per source.
//
// See ADR-0012 for the design rationale.

export interface ScanInput {
  sourceId: string;
  url: string;
  feedUrl: string | null;
  kind: string;
  language: string;
  region: string | null;
  sdgFocus: string[];
}

export interface ScannedFinding {
  url: string;
  title: string;
  summary: string | null;
  language: string;
  publishedAt: Date | null;
  sdgFocus: string[];
  region: string | null;
}

export interface Scanner {
  readonly kind: string;
  scan(input: ScanInput): Promise<ScannedFinding[]>;
}

// Minimal stub scanner used in MVP and tests. Real scanners (RSS via
// fast-xml-parser, HTML via cheerio, GitHub via @octokit/rest) plug in here.
export class StubScanner implements Scanner {
  readonly kind = 'stub';
  async scan(input: ScanInput): Promise<ScannedFinding[]> {
    return [
      {
        url: input.url,
        title: `(stub) Weekly check of ${input.url}`,
        summary:
          'This is a placeholder finding generated by the stub scanner. Real scanners produce findings from the upstream source.',
        language: input.language,
        publishedAt: new Date(),
        sdgFocus: input.sdgFocus,
        region: input.region,
      },
    ];
  }
}

export function pickScanner(kind: string): Scanner {
  // MVP: every kind routes to the stub. Real adapters slot in here.
  switch (kind) {
    default:
      return new StubScanner();
  }
}
